//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLLM {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    public sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint dlbps3074 {
            get {
                return ((uint)(this["dlbps3074"]));
            }
            set {
                this["dlbps3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint ulbps3074 {
            get {
                return ((uint)(this["ulbps3074"]));
            }
            set {
                this["ulbps3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color dlbg3074 {
            get {
                return ((global::System.Drawing.Color)(this["dlbg3074"]));
            }
            set {
                this["dlbg3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color dlfg3074 {
            get {
                return ((global::System.Drawing.Color)(this["dlfg3074"]));
            }
            set {
                this["dlfg3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ulbg3074 {
            get {
                return ((global::System.Drawing.Color)(this["ulbg3074"]));
            }
            set {
                this["ulbg3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ulfg3074 {
            get {
                return ((global::System.Drawing.Color)(this["ulfg3074"]));
            }
            set {
                this["ulfg3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint dlbps7500 {
            get {
                return ((uint)(this["dlbps7500"]));
            }
            set {
                this["dlbps7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint ulbps7500 {
            get {
                return ((uint)(this["ulbps7500"]));
            }
            set {
                this["ulbps7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color dlbg7500 {
            get {
                return ((global::System.Drawing.Color)(this["dlbg7500"]));
            }
            set {
                this["dlbg7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color dlfg7500 {
            get {
                return ((global::System.Drawing.Color)(this["dlfg7500"]));
            }
            set {
                this["dlfg7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ulbg7500 {
            get {
                return ((global::System.Drawing.Color)(this["ulbg7500"]));
            }
            set {
                this["ulbg7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ulfg7500 {
            get {
                return ((global::System.Drawing.Color)(this["ulfg7500"]));
            }
            set {
                this["ulfg7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint dlbps27k {
            get {
                return ((uint)(this["dlbps27k"]));
            }
            set {
                this["dlbps27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint ulbps27k {
            get {
                return ((uint)(this["ulbps27k"]));
            }
            set {
                this["ulbps27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color dlbg27k {
            get {
                return ((global::System.Drawing.Color)(this["dlbg27k"]));
            }
            set {
                this["dlbg27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color dlfg27k {
            get {
                return ((global::System.Drawing.Color)(this["dlfg27k"]));
            }
            set {
                this["dlfg27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ulbg27k {
            get {
                return ((global::System.Drawing.Color)(this["ulbg27k"]));
            }
            set {
                this["ulbg27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ulfg27k {
            get {
                return ((global::System.Drawing.Color)(this["ulfg27k"]));
            }
            set {
                this["ulfg27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color bgd2ol {
            get {
                return ((global::System.Drawing.Color)(this["bgd2ol"]));
            }
            set {
                this["bgd2ol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color fgd2ol {
            get {
                return ((global::System.Drawing.Color)(this["fgd2ol"]));
            }
            set {
                this["fgd2ol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color bggp {
            get {
                return ((global::System.Drawing.Color)(this["bggp"]));
            }
            set {
                this["bggp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color fggp {
            get {
                return ((global::System.Drawing.Color)(this["fggp"]));
            }
            set {
                this["fggp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color bgpvp {
            get {
                return ((global::System.Drawing.Color)(this["bgpvp"]));
            }
            set {
                this["bgpvp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color fgpvp {
            get {
                return ((global::System.Drawing.Color)(this["fgpvp"]));
            }
            set {
                this["fgpvp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color bg30kkc {
            get {
                return ((global::System.Drawing.Color)(this["bg30kkc"]));
            }
            set {
                this["bg30kkc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color fg30kkc {
            get {
                return ((global::System.Drawing.Color)(this["fg30kkc"]));
            }
            set {
                this["fg30kkc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint bpslfg {
            get {
                return ((uint)(this["bpslfg"]));
            }
            set {
                this["bpslfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color bglfg {
            get {
                return ((global::System.Drawing.Color)(this["bglfg"]));
            }
            set {
                this["bglfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color fglfg {
            get {
                return ((global::System.Drawing.Color)(this["fglfg"]));
            }
            set {
                this["fglfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public uint bps30k {
            get {
                return ((uint)(this["bps30k"]));
            }
            set {
                this["bps30k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color bg30k {
            get {
                return ((global::System.Drawing.Color)(this["bg30k"]));
            }
            set {
                this["bg30k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color fg30k {
            get {
                return ((global::System.Drawing.Color)(this["fg30k"]));
            }
            set {
                this["fg30k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color bghpved {
            get {
                return ((global::System.Drawing.Color)(this["bghpved"]));
            }
            set {
                this["bghpved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color fghpved {
            get {
                return ((global::System.Drawing.Color)(this["fghpved"]));
            }
            set {
                this["fghpved"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\xboxgames\\destiny 2 (pc)\\content\\destiny2.exe")]
        public string AppPath {
            get {
                return ((string)(this["AppPath"]));
            }
            set {
                this["AppPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeydl3074 {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeydl3074"]));
            }
            set {
                this["modkeydl3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keydl3074 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keydl3074"]));
            }
            set {
                this["keydl3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeyul3074 {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeyul3074"]));
            }
            set {
                this["modkeyul3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keyul3074 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keyul3074"]));
            }
            set {
                this["keyul3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeydl7500 {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeydl7500"]));
            }
            set {
                this["modkeydl7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keydl7500 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keydl7500"]));
            }
            set {
                this["keydl7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeyul7500 {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeyul7500"]));
            }
            set {
                this["modkeyul7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keyul7500 {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keyul7500"]));
            }
            set {
                this["keyul7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeydl27k {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeydl27k"]));
            }
            set {
                this["modkeydl27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keydl27k {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keydl27k"]));
            }
            set {
                this["keydl27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeyul27k {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeyul27k"]));
            }
            set {
                this["modkeyul27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keyul27k {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keyul27k"]));
            }
            set {
                this["keyul27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkey30kl {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkey30kl"]));
            }
            set {
                this["modkey30kl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys key30kl {
            get {
                return ((global::System.Windows.Forms.Keys)(this["key30kl"]));
            }
            set {
                this["key30kl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkey30kkc {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkey30kkc"]));
            }
            set {
                this["modkey30kkc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys key30kkc {
            get {
                return ((global::System.Windows.Forms.Keys)(this["key30kkc"]));
            }
            set {
                this["key30kkc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeylfg {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeylfg"]));
            }
            set {
                this["modkeylfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keylfg {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keylfg"]));
            }
            set {
                this["keylfg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeypvpl {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeypvpl"]));
            }
            set {
                this["modkeypvpl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keypvpl {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keypvpl"]));
            }
            set {
                this["keypvpl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeygp {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeygp"]));
            }
            set {
                this["modkeygp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keygp {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keygp"]));
            }
            set {
                this["keygp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NLMMB.Src.ModKeys modkeypvel {
            get {
                return ((global::NLMMB.Src.ModKeys)(this["modkeypvel"]));
            }
            set {
                this["modkeypvel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.Forms.Keys keypvel {
            get {
                return ((global::System.Windows.Forms.Keys)(this["keypvel"]));
            }
            set {
                this["keypvel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeydl3074 {
            get {
                return ((bool)(this["hotkeydl3074"]));
            }
            set {
                this["hotkeydl3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeyul3074 {
            get {
                return ((bool)(this["hotkeyul3074"]));
            }
            set {
                this["hotkeyul3074"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeydl7500 {
            get {
                return ((bool)(this["hotkeydl7500"]));
            }
            set {
                this["hotkeydl7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeyul7500 {
            get {
                return ((bool)(this["hotkeyul7500"]));
            }
            set {
                this["hotkeyul7500"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeydl27k {
            get {
                return ((bool)(this["hotkeydl27k"]));
            }
            set {
                this["hotkeydl27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeyul27k {
            get {
                return ((bool)(this["hotkeyul27k"]));
            }
            set {
                this["hotkeyul27k"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkey30kl {
            get {
                return ((bool)(this["hotkey30kl"]));
            }
            set {
                this["hotkey30kl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkey30kkc {
            get {
                return ((bool)(this["hotkey30kkc"]));
            }
            set {
                this["hotkey30kkc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeygp {
            get {
                return ((bool)(this["hotkeygp"]));
            }
            set {
                this["hotkeygp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeypvpl {
            get {
                return ((bool)(this["hotkeypvpl"]));
            }
            set {
                this["hotkeypvpl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeypvel {
            get {
                return ((bool)(this["hotkeypvel"]));
            }
            set {
                this["hotkeypvel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool hotkeylfg {
            get {
                return ((bool)(this["hotkeylfg"]));
            }
            set {
                this["hotkeylfg"] = value;
            }
        }
    }
}
